### ISSUE TITLE
Tidy up design of membership courses

### ISSUE THREAD

**Issue by nicolabird** [Simplero/Roadmap#155]
The new membership courses look great on mobile - way better than spaces :)

However on a desktop it would be great if the design could be tidied up - I'm not a designer so I can make suggestions but generally yearghhh, this looks visually cluttered and is the main reason I'm not moving to courses just yet.

https://www.dropbox.com/s/rk6ahei3qi6pjrs/Screenshot%202017-10-18%2014.16.10.png?dl=0

Perhaps you could
1. Give us as choice if we want the 'complete and continue' button - it would forgo that option just to make the page look nicer and my clients don't need it.

2. If we have to keep the button, make it tie in the theme options - I've selected a blue colour for buttons but this button is still showing as green.

3. Video and audio player to be same width so that the download text under both is balanced equally under the element  as it is in spaces https://www.dropbox.com/s/8okj3g4n7x74vaa/Screenshot%202017-10-18%2014.21.15.png?dl=0

4. Remove big space between text and additionally added media

5. Ability to add same elements to course lessons and modules as you can to pages which would allow us more flexibility to design/add images etc - the screen is VERY black and white and un-coachy (if that makes sense)

6. Collapse lessons into modules in sidebar as suggested in other ticket.

**Comment by nickbruun** [comment]
Hi Nicola,

Thank you for your suggestions. Some of these I'd love to have seen broken down for future reference so we can discuss them individually (they also overlap some other requests.)

However:

1. Good idea. That's now an option in the administrative interface.
2. The intention was indeed to make it possible for you to change this color. It's now in the theme customization interface as the _Success accent color_ under _Colors_
3. I've blown the videos up to full width now :)
4. This is intentional to separate the two
5. The simpler nature of course lessons is by design, so that we can more easily present it in different formats down the line. While I do understand the desire to be able to add sections and elements, it's currently not the intention to be able to do so

I hope this answers suggestions :)

**Comment by nicolabird** [comment]
1. Wow - great thank you Nick!
2. Thank you!
3. Thank you!
4. OK
5. OK - fascinated by the longer term vision - will edit my course accordingly to include 1 video per lesson....
