### ISSUE TITLE
Ability to add content and media in courses in the same way as in spaces

### ISSUE THREAD

**Issue by nicolabird** [Simplero/Roadmap#156]
Where I have several elements in one lesson, I am unable to space them how I want to.

For example this lesson has 4 videos and I want to be able to put text between each one to introduce them. I can do this in spaces but not in courses.

https://www.dropbox.com/s/9d0dx6fkfilrm23/Screenshot%202017-10-18%2014.27.10.png?dl=0

I know I can create 4 lessons but I am delivering one lesson per week and sometimes I want to include more than one video in a lesson.

**Comment by nickbruun** [comment]
Course lessons are built and designed to only have one video per lessons so we can do a number of more interesting things with them down the line (think being able to stream it continuously on Apple TV, in an iPhone app etc.). While you can embed other videos like you've done, it's not the intended use, so this is not something that we're looking to change. I understand that this is more restrictive than Spaces, but it's by design, so that we can do other things down the line :)
