### ISSUE TITLE
Membersite - more videoes in one lesson

### ISSUE THREAD

**Issue by ChristinaChristiansen** [Simplero/Roadmap#168]
I would love the possibility to add more video's than one i one lesson.
I order to keep "lessons" limited and make my students see the small steps within "one lesson" clearly... (I do not want them to have long videos)

Hope this will be possible :-)

**Comment by nickbruun** [comment]
The way courses are designed and built, this is likely not going to change. The idea is to have one piece of media per lesson, so that it can more easily be presented on other platforms down the line. This includes for example Apple TV, where it's very hard to have content interleaved. For now therefore, this is not something we're going to change. I know it's not ideal for all types of content, but the "restriction" in this way opens up a lot of opportunities down the line, which is one of the reasons why we introduced the more structured courses in the first place.
