### ISSUE TITLE
Show members progress in course

### ISSUE THREAD

**Issue by CoachWouter** [Simplero/Roadmap#183]
Hi Nick,

I would like to see how far members have progressed in a course (on a membership site). Could this be shown on the course Summary or Members screen? It will help me track and support their engagement, and spot problems early. 

Sherrie recommended me to request it here. Looking forward to your feedback. 

Kind regards,

Wouter

**Comment by nickbruun** [comment]
If you go to view a member of a membership site in the administrative interface, you will see that under the section "Courses they have access to" along with listing the accessible content, there will be checkmarks to the right of the individual lessons marked as completed by the member. It also shows when the lesson was completed.

Is this different from what you're requesting?

**Comment by CoachWouter** [comment]
Hi Nick, thanks. What you are pointing to is an individual member view. How about a view for all members of a course?

**Comment by frejaelise** [comment]
I have the same request, and also that it would be possible to put tags on completion at some certain points, say for example when completed a module. If I could do that, then I could adapt the automations so that a reminder-email only is send to the customers who haven't completed the module.

I don't see "Courses they have access to" - could that be because I don't have a product connected to the course (because it is a free course and you get access to the membership site --> with the course)? Would love if it was easy to see how far customers have come, no matter what.

**Comment by calvincorreli** [comment]
I believe this has been implemented now.
