### ISSUE TITLE
Feature request: possibility to select "wait for day of month" in automations

### ISSUE THREAD

**Issue by infospray** [Simplero/Roadmap#2]
I would like to run an automation sequence starting each of the 1th in the month.

See: https://www.evernote.com/l/ACDFPA75nDZPkK54mR5r1o6IT9EG7tzql-c

This would be awesome and supplement the "wait until 'monday'" functionality.

**Comment by calvincorreli** [comment]
That's a good idea. Not too hard to do, actually (though, yes, harder than the other one). I'm taking a look.

**Comment by calvincorreli** [comment]
Hey, I have this implemented, but before I deploy, I wanted to ask for your input. Nick and I disagree on the semantics of how exactly it should work.

Here's how I have it:

![Screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/272V1f062G2w2Q0o2c23/Screen%20Shot%202017-04-04%20at%206.30.12%20PM.png)

If you select the 1st of the month, well that's obvious.

If you select last day of the month, or second to last day of the month, that, too, is obvious.

But what happens when you select the 31st of the month?

Two options:

1. Interpret it as meaning "Last day of the month", so that if you're in February and it's not a leap year, it means the 28th. Feb in a leap year, it really means the 29th. April, it means the 30th. May, it means the 31st.

2. Interpret it as meaning literally the 31st of the month. So if you're in February, it would take you to March 31st. If you're in March, it would also take you to March 31st. If you're in April, it would take you to May 31st.

Thoughts?

**Comment by infospray** [comment]
That's awesome. I really just wanted something that could run every 1st in each month, so I hadn't really considered the problem of setting it to the 31th in the month and then not having it run in say February. 

A couple of thoughts. 

1) It's awesome that you thought of this

2) If I said it to the 31st, it is by choice and I would not expect it to run in say February (or months with only 30 days).

3) I'm not quite sure what you mean by "Second to last day of the month" or the use case for it, but I'm sure you have a good reason for this. In order to keep it simple, you could omit this in the first version (and hopefully not give you too much support ;)).

**Comment by calvincorreli** [comment]
Made a few tweaks, and it's now live. Thanks for the suggestion.
