### ISSUE TITLE
Disable/enable text message when a product is sold

### ISSUE THREAD

**Issue by dortelytje** [Simplero/Roadmap#217]
I am often missing the opportunity to disable the (beloved) textmessage I have chosen to receive when I sell a product. I love getting these messages, but since I am also using 'products' for free products I would be nice to be able to disable the text-me-feature on these products, but still have them on my normal paying products.
Is this possible?

**Comment by calvincorreli** [comment]
Sort-of. 

Remove your phone number under Settings > Product > Notifications > Send an SMS notification of each new purchase.

Instead, add a trigger with "Billing contact: Activated, first time only" action "Notification text message" for each product that you do want to be notified about.

Or use lists instead of products for the free stuff.

**Comment by dortelytje** [comment]
Thank you for the reply, Calvin. I think I'll try your first solution.

The reasons why I'm sometimes using products instead of lists are:
1. the Danish government has made it illegal to use the word FREE for freebies if it means that people have to sign up, so by using a free product instead I can call it FREE  because people have the opportunity to say no to emails.
2. by using products I can add these (free courses / bonuses) as an upsell.
