### ISSUE TITLE
Promo code

### ISSUE THREAD

**Issue by Livskvalitetspartner** [Simplero/Roadmap#301]
I have a big problem with customers writing me asking: How / where can i use this Rabat-kode/promo code you gave me?

They can't find the pace for tying in the code. In my shop it is shown as a gray tekst: "Har du en rabat-kode?" But it is not clear that the tekst is a link. 

Please make the place for promo codes easy to find.
At least make the tekst blue to show you can tap, for reading more.

Using promo codes is a very important tool in campaigns but if the customer can't find the place to use the code they will not buy at all. I have ben using a lot of money on campaigns and im sorry to see that so many people haven't been able to find the place to type the Rabat-kode. 

So in my opinion the place to write the Promo code/ rabat kode, should be very very very easy to spot.

**Comment by calvincorreli** [comment]
I totally understand, but it's not that sipmel.

And when we had that, we got complaints that it was too prominent, because it made people worry that they were paying full price for something that others get for a discount. If you have a coupon code, you'll be looking for a place to enter it. If you don't, we want it to be unobtrusive. 

I don't see a solution that's going to make everyone happy. This seems to hit the spot for the majority of customers and cases.
