### ISSUE TITLE
Removing unsubscribers

### ISSUE THREAD

**Issue by lisajane-jones** [Simplero/Roadmap#4]
When someone unsubscribes all their details are removed not just set to do not contact. It's really difficult to track numbers when they are still on the system and it makes on sense to keep them there.

**Comment by calvincorreli** [comment]
Hi Lisajane,

What numbers specifically are you looking to track that are more difficult because of past subscribers being in the system?

One reason we keep them is, if we delete them, links in emails already sent would stop working, and we'd have no record of what we'd sent to whom. If someone resubscribes later, or reopens an old email and clicks a link, it's still relevant to know.

I've personally never experienced problems with past subscribers being in the system, so I'm curious what specific issues you've run into so I can understand the problem better.
