### ISSUE TITLE
Like option in membership site

### ISSUE THREAD

**Issue by AnjaBusack** [Simplero/Roadmap#439]
I would very much appreciate a LIKE option in all communication platforms in membership sites.

**Comment by BethKBJ** [comment]
Hi Anja!  

Thanks for writing. Help me understand which things exactly you want your members to be able to 'like'...  

- Comments on Lessons
- Blog posts
- Blog comments
- Forum posts
- Forum comments

What else am I missing?  

Thanks!
Beth

**Comment by AnjaBusack** [comment]
Hey Beth,
yes exactly - the LIKE option in comment boxes, like we have it in Spaces. It is a very nice way to indicate, that the comment is read - without having to comment further 

Im not sure what the difference is between posts and comments? ... but Im guessing, what Im asking for is the LIKE option in comments :)

**Comment by BethKBJ** [comment]
Got it.  The 'like' option for comments on all of the above stuff I listed.  

Let's give it a bit and see how many other folks think this would be valuable to them.  We'll keep it in mind next time we work on general improvements to membership sites.  

Thanks!!

**Comment by tracyleigh54** [comment]
I agree that I would enjoy a like button in membership site forum and all places mentioned (As Anja says so you can indicate it was read without having to reply further). It IS in spaces on forum posts -- but my feedback is that the feature needs improvement because you don't get any notification of the like, and it doesn't say who gave the like. So its sort of like the like never happened.

**Comment by mylesboone** [comment]
Hi @AnjaBusack this was deployed just now. We hope you 'like' it :)
