### ISSUE TITLE
Automatically set default video fram to frame 2 or 3 - to avoid boring video stills 

### ISSUE THREAD

**Issue by jesperconrad** [Simplero/Roadmap#456]
I presume I am not the only one who has a video that start either with a fade in from black or white or with a title screen. Neither of which creates a great video-still. Actually my experience is, that all my default frames are black... And then i have to go in and choose a default frame.

Both Youtube, Facebook and Vimeo, chooses another frame than frame 1, so I would love If you could change the default frame to frame 2 or 3 - then I believe that you would save many people from having to choose another frame.

**Comment by jesperconrad** [comment]
![black-frames](https://user-images.githubusercontent.com/9960764/52173662-e86cf100-2788-11e9-8cbf-f97cae57efc4.png)

**Comment by calvincorreli** [comment]
The reason it grabs the first frame by default is that a lot of videos will have a title screen that says what the video is about, and so we want to capture that. If we grabbed a little later, then they'd all look the same in that case.

YouTube generally grabs a frame from the exact middle of the video, which is generally less useful in our case.

Why do your videos fade from black, do you know? Is that intentional?

**Comment by calvincorreli** [comment]
I'm going to start grabbing both the frame at the very start, and the one half a second in, and default to the one at a half second, and see if that works better. It should.

**Comment by jesperconrad** [comment]
Thank you - So happy for this :)
