### ISSUE TITLE
New Purchase - contact info import - needs

### ISSUE THREAD

**Issue by MatenPet** [Simplero/Roadmap#47]
Hello Nick, I have something that you may want to take a look at, I have made pdf of screenshots and notes in them. It is regarding new members contact info after they purchase our product and become new contacts. See attached. I love Simplero and what you do and that you can improve things at the drop of a hat. If you have designed simplero to work the way the screenshots will show you than I will continue with my work-arounds. However, I feel that if no one tells you this is a problem, it can't be fixed. :)
[simplero screenshot help.pdf](https://github.com/Simplero/Roadmap/files/1015618/simplero.screenshot.help.pdf)

**Comment by calvincorreli** [comment]
Hey Maten,

A lot of that is because of the way you've aded the custom fields.

When you add a field of type "Address", it comes complete with line 1, line 2, zip, state, country. You don't need to add those separately. Those are just for if you want to have a field where you ask for country or state, without asking for a complete address.

Hope that helps.
