### ISSUE TITLE
Change the Unsubscribe page

### ISSUE THREAD

**Issue by cipriansoleriu** [Simplero/Roadmap#50]
Since I moved from Active Campaign to Simplero I got marked a lot of times as spam by people that unsubscribed.

First I thought it was strange because in Active Campaign this rarely happened... but then I saw the page that Simplero presents to people that unsubscribes. 
It's like it invites them to mark as spam...big red button... 
This impacts negatively the deliverability and all the jazz.. :)

Take a look (img 1) 
![image](https://cloud.githubusercontent.com/assets/3611728/26524355/f8328c84-4338-11e7-8cf5-7a68ea4a4861.png)

Can you make something to offer people the option to mark as spam but not as the only option that they have?

Maybe something like Active Campaign does? 
(see image 2)
![image](https://cloud.githubusercontent.com/assets/3611728/26524358/029bdc70-4339-11e7-9c5d-ffef76bd75d8.png)

Thanks a lot, 
Ciprian

**Comment by calvincorreli** [comment]
Ciprian, thanks for the suggestion.

Just to clarify, though. Hitting this button does NOT impact deliverability or reputation or anything like that negatively. That spamreport only goes to Simplero, which is the point. It lets people express their feeling that this is spam, without hurting you in any way.

It's valuable info for both you and us, as we aim to keep the reputation up. It's a million times better that they report as spam using that button rather than through their email client.

Hope that clarifies.

**Comment by cipriansoleriu** [comment]
Got it.
It's OK then :)

I still think the button is a little too 'in their face' :)

Thanks for the clarification Calvin!
Cipri

În dum., 28 mai 2017 la 00:08 Calvin Correli <notifications@github.com> a
scris:
