### ISSUE TITLE
For worksheets, allow dialogue between owner/teacher and client/member/student

### ISSUE THREAD

**Issue by PlanetThoughts** [Simplero/Roadmap#8]
For coaching, or generally for support, it would be useful to allow the owner (or designated individual) to respond to the way a client/member fills in a worksheet. There should be the ability to have dialogue back and forth.

Specifically, the creator of the worksheet could ideally indicate one of three choices as part of the worksheet definition: 1) no dialogue (it is simply a product for sale for self-study), 2) dialogue on the overall worksheet (not for individual questions), or 3) dialogue allowed on a per-question basis, after the client/member has responded to the question or questions.

This would make Simplero a good replacement for a product like JigsawBox. For a true LMS it is important to allow direct comment and interchange between teacher/designee/owner and client/member, for the full value of the learning product. Since Simplero is supporting the sale of digital products, it would be good for Simplero as well as their user community to have this feature available for digital products.

**Comment by CoachWouter** [comment]
Strongly support this. After leaving JigsawBox for other reasons, I have always missed that. I'm now supporting my coaching interactions through CoachingCloud, which I find clunky, and would dearly like to include coaching work in Simplero as my single platform. Since there are many coaches in the market place, this would serve current coaches in Simplero and be a wonderful reason for more coaches to join Simplero. For one-to-one coaching interaction, we need a private space additional to a community forum (or the option to PM people and have those exchanges logged). Normally we want coachees to prepare for coaching sessions and also have notes afterwards. I realize this would be a large expansion of Simplero, yet there is a large number of coaches who would want to use this.

**Comment by ManjirS** [comment]
Support this too. I am also a Jigsawboxer and ideally would like to leave completely in the future.

**Comment by tueolesen** [comment]
My vote for this one too: Would take the potential of using worksheets inside a course to a new level - getting the dialogue going with clients and keeping a track of that dialogue in worksheets would be a powerful addition!

**Comment by CoachWouter** [comment]
Looking forward to feedback from @calvincorreli if and how this can be done. Tapping into the coaching market is a significant business opportunity for Simplero, I believe. And even from the point of view of online education, the market is moving to engaging with learners rather than only selling and delivering courses.

**Comment by calvincorreli** [comment]
It's definitely something that's on our minds, and on our shortlist. I'll mark it as such here.

**Comment by ManjirS** [comment]
Yay! Great news. :)

**Comment by ManjirS** [comment]
Hello Simplero Jigsawbox is in meltdown as they are so-called 'upgrading'. I have VIP clients ready and willing to go into programs with me and I don't have the right software to do these one-to-one coaching sessions within Simplero. I was hoping Jigsawbox might get there act together but it has got worse and in any case, I really don't want two systems. 

So I have people wanting to give me money and me wanting to take it yet the software is letting me down. This feature would make a lot of difference.

**Comment by ManjirS** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/fe4a1c10-cce9-4b4a-a43c-6e707afcc5d1-ded70cb8-fdca-43e1-aaa7-adc8e059098a-v1.png?transparent=1&palette=1&width=246)

**Comment by calvincorreli** [comment]
I hear you. Let's see if we can't help you out.

**Comment by calvincorreli** [comment]
Conversation around worksheets dropped.

See here for details:

http://cloud.smpl.ro/0X3W3W0F0N2P

Let me know what you think, and whether this hits the spot for you guys.

–Calvin

**Comment by calvincorreli** [comment]
Wrong link posted above. Here's the correct one: http://cloud.smpl.ro/0Q3d3s3I3v3w

**Comment by ManjirS** [comment]
Thank you so much. Honestly, if there was a Nobel Prize for software you should get it, Calvin. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/b60cb965-cc0a-4365-8d1f-8d56e9255948-ded70cb8-fdca-43e1-aaa7-adc8e059098a-v1.png?transparent=1&palette=1&width=246)
