### ISSUE TITLE
possibility to add a trigger to a list footer

### ISSUE THREAD

**Issue by ingjerd123** [Simplero/Roadmap#85]
I am making my own unsubscribe footer in the emails to make it easier for my subscribers to unsubscribe (many are beginners in the language, so the simplero footer can be hard to understand for some). Since I have more than one list, I have made an automation where they unsubscribe from everything when the unsubscribe link is clicked.

The problem is I cannot have this text in the list footer, because I cannot add a TRIGGER to the link there to start the automation. Which means I have to copy this text and add it to every email AND add the trigger to the link every time. This takes extra time, and in addition it doesn't look so pretty because it seems like its a part of the email.

So ... any chance you could make it possible to add triggers to the newsletter list footers?

**Comment by deannabuoniconti** [comment]
@ingjerd123  This is a little backwards, but you can use the auto subscribe link (and name it "unsubscribe) to a list, and have the list trigger your automation to start and add that to your footer.

**Comment by calvincorreli** [comment]
Ingjerd, I appreciate the sentiment, but I'd much rather figure out why it seems to be hard for your subscribers to unsubscribe, and fix that.

What seems to be the issue? They can't find the link, or they don't understand the page they get to?

There's a big button on that page that unsubscribes from everything. There's also the option to unsubscribe from each thing they're subscribed to individually. And there's the "nuclear option" of "never contact me again".

The idea is that you can be subscribed to one thing (newsletter), without being subscribed to something else (campaign for a specific product you know you're not interested in).

By doing this, you're removing that option.

Maybe you just have too many lists?

Would love to get to the root of this issue rather than band-aid it.

Also, what language are these people beginners in? We can set you up to translate anything on that page into any language you want.

**Comment by ingjerd123** [comment]
Hi, thanks for the replies

Of active lists, I have a free course, a newsletter and a waiting list for a paid product. I don't think it's too much, I need it to be that way.

I make Norwegian courses for immigrants in Norway. Everything I write is in Norwegian, and my subscribers are from all over the world. The only language they have in common, is Norwegian, cause it's far from everyone that understands English. The Simplero translations to Norwegian are easy to understand for a Norwegian, but it can be quite hard for someone who is new in learning the language. I even have paying, very satisfied customers hitting the spam button by accident, and I don't have a number for how many times people unsubscribe (or hitting spam) from my free course and afterwords contacting me asking why they're not getting any more emails. I year ago I suggested it would be much clearer if you would add some visuals to the buttons, so you don't need to understand every word to hit the right button (or maybe stay away from touch it)

Anyways, this is the reason I have made my own unsubscribe footer with a trigger that unsubscribe from everything.

**Comment by calvincorreli** [comment]
So the request here is "add icons to unsubscribe page?"

**Comment by ingjerd123** [comment]
yes, that would help a lot

Ingjerd

2017-08-09 22:11 GMT+02:00 Calvin Correli <notifications@github.com>:

**Comment by ingjerd123** [comment]
but it would also be nice to be able to add a trigger to a list footer ...

2017-08-09 23:50 GMT+02:00 Ingjerd Eriksen Hovde <ingjerd.hovde@gmail.com>:

**Comment by calvincorreli** [comment]
Does the new unsubscribe page solve the issues?

If not, please open a new feature requests with specifics for what you'd like to see changed there to make it better work for you and your audience.

**Comment by ingjerd123** [comment]
Yes, I believe it's much better. Time will tell. If not I'll make a new request in some months
